<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Upgrade steps for Feedback Flow.
 *
 * @package    block_feedback_tracker
 * @copyright  2026 Anderson Blaine <anderson@blaine.com.br>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */



/**
 * v1.0.0 baseline — fresh installations only.
 *
 * `db/install.xml` is the canonical schema; the install hook in
 * `db/install.php` seeds defaults. This plugin supports new
 * installations only — sites running a hypothetical prior version
 * that try to upgrade get an explicit error message asking them
 * to uninstall and reinstall on a clean database.
 *
 * If you ever need to re-add upgrade steps (e.g. a v1.x schema change),
 * the standard pattern returns: `if ($oldversion < <version_code>) {
 * ...; upgrade_block_savepoint(true, <version_code>, 'feedback_tracker'); }`.
 *
 * @param int $oldversion The currently-installed plugin version code.
 * @return bool True on success.
 * @throws upgrade_exception When an unsupported pre-v1 version is detected.
 */
function xmldb_block_feedback_tracker_upgrade($oldversion) {
    global $DB;
    /*
     * Fresh installs land here with $oldversion = 0 (the install hook
     * sets the version *after* this function returns). Returning true
     * for that case lets the install complete cleanly.
     *
     * Any non-zero oldversion below the v1.0.0 baseline means the site
     * previously had an older release of this plugin and is now trying
     * to upgrade across the schema reset. Block it with a clear,
     * actionable message — silent migration could lose data.
     */
    if ($oldversion > 0 && $oldversion < 2026060100) {
        throw new upgrade_exception(
            'block_feedback_tracker',
            $oldversion,
            'Upgrades from versions before 1.0.0 are not supported. '
                . 'Please uninstall the plugin (Site admin → Plugins → '
                . 'Plugins overview → Uninstall block_feedback_tracker), '
                . 'drop any remaining mdl_block_feedback_tracker_* tables '
                . 'manually if the uninstall left them behind, then '
                . 'reinstall on a clean database. Ledger data will be '
                . 'regenerated by re-enabling Process historical '
                . 'submissions in the admin settings after install.'
        );
    }

    // V1.0.1 — seeds the new score_thresholds_band setting so 1.0.0
    // installs pick up the design defaults without waiting for an admin
    // to visit the settings page. The set_config() call deliberately
    // skips set_updatedcallback (which only fires through
    // admin_setting_*::write_setting), avoiding the bootstrap-guard
    // path during upgrade.
    if ($oldversion < 2026060101) {
        if (get_config('block_feedback_tracker', 'score_thresholds_band') === false) {
            set_config('score_thresholds_band', '90,70,40', 'block_feedback_tracker');
        }
        upgrade_block_savepoint(true, 2026060101, 'feedback_tracker');
    }

    // V1.0.2 — block-view recomposition. No DB changes; the new Preact
    // components and CSS tokens ship in code only. The savepoint is here so
    // sites still get a deterministic upgrade marker.
    if ($oldversion < 2026060102) {
        upgrade_block_savepoint(true, 2026060102, 'feedback_tracker');
    }

    // V1.0.3 — payload extensions (perceived / paused / peer). No schema
    // changes: perceived_median_hours aliases median_raw_h, paused aggregates
    // are computed at read time from cday + cpause, peer benchmarks come from
    // the existing _group rollup. Bump calver so MUC keys roll over and
    // cached payloads pick up the new keys on first access.
    if ($oldversion < 2026060103) {
        \block_feedback_tracker\local\calendar\calendar::bump_version();
        upgrade_block_savepoint(true, 2026060103, 'feedback_tracker');
    }

    // V1.0.4 — pending report page redesign. No DB changes; new Preact
    // components + bootstrap shape extension only. Savepoint here for the
    // upgrade marker, no cache bump (read-side payload shape unchanged).
    if ($oldversion < 2026060104) {
        upgrade_block_savepoint(true, 2026060104, 'feedback_tracker');
    }

    // V1.0.5 — dashboard redesign + new get_insights WS. The WS slots
    // into the existing dashboard cache; bump calver so per-user cached
    // dashboards re-fetch and pick up the new score_band / trend_series
    // / perceived_median_hours fields from get_dashboard.
    if ($oldversion < 2026060105) {
        \block_feedback_tracker\local\calendar\calendar::bump_version();
        upgrade_block_savepoint(true, 2026060105, 'feedback_tracker');
    }

    // V1.0.6 — web-service completion. Five new JS write wrappers
    // (savePauseWindow / deletePauseWindow / saveCalendarDay /
    // bulkImportCalendar / saveBusinessHours), one new read WS
    // (get_audit_log, gated by the existing viewaudit capability), and a
    // drift-check phpunit test. No DB changes; no cache bump (read-side
    // payload shape unchanged).
    if ($oldversion < 2026060106) {
        upgrade_block_savepoint(true, 2026060106, 'feedback_tracker');
    }

    // V1.0.7 — trend-term refinements (adaptive w_trend + dashboard
    // momentum). No DB changes. Existing rollup rows still have
    // comp_trend = 0.5 from prior versions; they'll converge to null on
    // the natural recompute cycle (event observers / drain queue) and
    // don't need a forced recompute here.
    if ($oldversion < 2026060107) {
        upgrade_block_savepoint(true, 2026060107, 'feedback_tracker');
    }

    // V1.0.8 — combined hero+insights collapse state persisted via the
    // core user-preferences API. No schema change; the preference key
    // (block_feedback_tracker_dashboard_collapsed) is declared in
    // lib.php::block_feedback_tracker_user_preferences() and gets a
    // server-side default of '0' so existing users see the expanded
    // hero on first visit after upgrade.
    if ($oldversion < 2026060108) {
        upgrade_block_savepoint(true, 2026060108, 'feedback_tracker');
    }

    // V1.0.9 — sub-day optional event windows. Two nullable columns
    // on {block_feedback_tracker_cday} for minutes-since-midnight
    // start / end. Both null = legacy full-day rule (existing rows are
    // unaffected). Calver bump invalidates cached payloads so the new
    // paused_events_30d sidecar shows up on next read.
    if ($oldversion < 2026060109) {
        $dbman = $DB->get_manager();
        $table = new xmldb_table('block_feedback_tracker_cday');

        $field = new xmldb_field(
            'starttime',
            XMLDB_TYPE_INTEGER,
            '4',
            XMLDB_UNSIGNED,
            null,
            null,
            null,
            'daytype'
        );
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        $field = new xmldb_field(
            'endtime',
            XMLDB_TYPE_INTEGER,
            '4',
            XMLDB_UNSIGNED,
            null,
            null,
            null,
            'starttime'
        );
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        \block_feedback_tracker\local\calendar\calendar::bump_version();
        upgrade_block_savepoint(true, 2026060109, 'feedback_tracker');
    }

    // V1.0.10 — patch the PHP 8.x "implicit float→int" deprecation in
    // paused_aggregator::ymd_in_pause_span. Code-only fix, no schema or
    // cache impact — the savepoint exists for the upgrade marker so any
    // sites that picked up 1.0.9 on PHP 8.1+ converge cleanly to 1.0.10
    // with the deprecation gone.
    if ($oldversion < 2026060110) {
        upgrade_block_savepoint(true, 2026060110, 'feedback_tracker');
    }

    // V1.0.11 — UX patch: event time + date in PausedCallout, event
    // sidecar surfaced in block PausedNote, "Recent event" chip on the
    // teacher dashboard. JS-only and lang-strings — no DB or cache
    // impact. Savepoint here for the upgrade marker.
    if ($oldversion < 2026060111) {
        upgrade_block_savepoint(true, 2026060111, 'feedback_tracker');
    }

    return true;
}
