<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Upgrade steps for Feedback Flow.
 *
 * @package    block_feedback_tracker
 * @copyright  2026 Anderson Blaine <anderson@blaine.com.br>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

/**
 * v1.0.0 baseline — fresh installations only.
 *
 * `db/install.xml` is the canonical schema; the install hook in
 * `db/install.php` seeds defaults. This plugin supports new
 * installations only — sites running a hypothetical prior version
 * that try to upgrade get an explicit error message asking them
 * to uninstall and reinstall on a clean database.
 *
 * If you ever need to re-add upgrade steps (e.g. a v1.x schema change),
 * the standard pattern returns: `if ($oldversion < <version_code>) {
 * ...; upgrade_block_savepoint(true, <version_code>, 'feedback_tracker'); }`.
 *
 * @param int $oldversion The currently-installed plugin version code.
 * @return bool True on success.
 * @throws upgrade_exception When an unsupported pre-v1 version is detected.
 */
function xmldb_block_feedback_tracker_upgrade($oldversion) {
    /*
     * Fresh installs land here with $oldversion = 0 (the install hook
     * sets the version *after* this function returns). Returning true
     * for that case lets the install complete cleanly.
     *
     * Any non-zero oldversion below the v1.0.0 baseline means the site
     * previously had an older release of this plugin and is now trying
     * to upgrade across the schema reset. Block it with a clear,
     * actionable message — silent migration could lose data.
     */
    if ($oldversion > 0 && $oldversion < 2026060100) {
        throw new upgrade_exception(
            'block_feedback_tracker',
            $oldversion,
            'Upgrades from versions before 1.0.0 are not supported. '
                . 'Please uninstall the plugin (Site admin → Plugins → '
                . 'Plugins overview → Uninstall block_feedback_tracker), '
                . 'drop any remaining mdl_block_feedback_tracker_* tables '
                . 'manually if the uninstall left them behind, then '
                . 'reinstall on a clean database. Ledger data will be '
                . 'regenerated by re-enabling Process historical '
                . 'submissions in the admin settings after install.'
        );
    }

    return true;
}
